{
    'name': 'Alandicted',
    'version': '1.1',
    'summary': 'Alandicted ERP System',
    'description': 'A custom ERP system with dashboard, inventory and project management',
    'category': 'Customizations',
    'author': 'Alandicted',
    'website': '',
    'license': 'LGPL-3',
    'depends': ['base', 'web'],
    'data': [
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'views/common_templates.xml',
        'views/dashboard_templates.xml',
        'views/inventory_templates.xml',
        'views/project_templates.xml',
        'views/project_report.xml',
        'views/debug_template.xml',
        'views/menu.xml',
    ],
    'application': True,
    'installable': True,
    'auto_install': False,
} 